In [1]:
import cv2
import numpy as np

In [4]:
img = cv2.imread('../data/images/image.png')

## Learning Python OpenCV / Lesson #2 – Working with Images and Videos

In [5]:
cv2.imshow('Result', img)
cv2.waitKey(0)

QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.githu

-1

In [ ]:
img.shape

(1080, 1920, 3)

In [ ]:
# proportional resizing
reduction_factor = 2
h = img.shape[0] / 2
w = h * (img.shape[1] / img.shape[0])
print(h:=int(h), w:=int(w))
new_img_proportional_resizing = cv2.resize(img, (
    w,
    h, 
))
cv2.imshow('Result', new_img_proportional_resizing)
cv2.waitKey(0)

368 684


-1

In [ ]:
# proportional resizing 2
# arbitrary resizing
new_img_arbitrary_resizing = cv2.resize(img, (
    300,
    500, 
))
cv2.imshow('Result', new_img_arbitrary_resizing)
cv2.waitKey(0)

-1

In [ ]:
reduction_factor = 3
new_img_proportional_resizing = cv2.resize(img, (
    img.shape[1] // reduction_factor,
    img.shape[0] // reduction_factor, 
))
cv2.imshow('Result', new_img_proportional_resizing)
cv2.waitKey(0)

-1

In [ ]:
# cropped image
cropped_img = img[0:200, 0:300]
cv2.imshow('Result', cropped_img)
cv2.waitKey(0)

-1

In [ ]:
# gaussian blur
gaussian_blur_img = cv2.GaussianBlur(img, (19, 19), 0)
cv2.imshow('Result', gaussian_blur_img)
cv2.waitKey(0)

-1

In [ ]:
gaussian_blur_img_cvt = cv2.cvtColor(gaussian_blur_img, cv2.COLOR_BGR2GRAY) 
cv2.imshow('Result', gaussian_blur_img_cvt)
cv2.waitKey(0)

-1

In [ ]:
gaussian_blur_img_cvt_canny = cv2.Canny(gaussian_blur_img_cvt, 90, 90)
cv2.imshow('Result', gaussian_blur_img_cvt_canny)
cv2.waitKey(0)

-1

In [ ]:
kernel = np.ones((5, 5), np.uint8)
print(f'kernel: \n{kernel}')

gaussian_blur_img_cvt_canny_dilate = cv2.dilate(gaussian_blur_img_cvt_canny, kernel=kernel, iterations=2)

cv2.imshow('Result', gaussian_blur_img_cvt_canny_dilate)
cv2.waitKey(0)

kernel: 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


-1

In [ ]:
gaussian_blur_img_cvt_canny_dilate_erode = cv2.erode(gaussian_blur_img_cvt_canny, kernel=kernel, iterations=2)

cv2.imshow('Result', gaussian_blur_img_cvt_canny_dilate)
cv2.waitKey(0)

-1

## Learning Python OpenCV / Lesson #3 – Creating Objects and Outputting Information

In [2]:
photo = np.zeros((300, 300, 3), dtype='uint8')

In [3]:
photo

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(300, 300, 3), dtype=uint8)

In [4]:
cv2.imshow('Result', photo)
cv2.waitKey(0)

QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.githu

-1