In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('../data/images/image.png')

In [3]:
def open_photo(photo):
    cv2.imshow('Result', photo)
    cv2.waitKey(0)

In [4]:
def rotate(image, angle):
    height, width = image.shape[:2]
    point = (width // 2, height // 2)

    mat = cv2.getRotationMatrix2D(point, angle, 1)
    return cv2.warpAffine(image, mat, (width, height))

In [5]:
def transform(img_param, x, y):
    mat = np.float32([[1, 0, x], [0, 1, y]])
    return cv2.warpAffine(img_param, mat, (img_param.shape[1], img_param.shape[0]))

## Learning Python OpenCV / Lesson #2 – Working with Images and Videos

In [5]:
open_photo(img)

QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.githu

-1

In [ ]:
img.shape

(1080, 1920, 3)

In [ ]:
# proportional resizing
reduction_factor = 2
h = img.shape[0] / 2
w = h * (img.shape[1] / img.shape[0])
print(h:=int(h), w:=int(w))
new_img_proportional_resizing = cv2.resize(img, (
    w,
    h, 
))
open_photo(new_img_proportional_resizing)

368 684


-1

In [ ]:
# proportional resizing 2
# arbitrary resizing
new_img_arbitrary_resizing = cv2.resize(img, (
    300,
    500, 
))
open_photo(new_img_arbitrary_resizing)

-1

In [ ]:
reduction_factor = 3
new_img_proportional_resizing = cv2.resize(img, (
    img.shape[1] // reduction_factor,
    img.shape[0] // reduction_factor, 
))
open_photo(new_img_proportional_resizing)

-1

In [ ]:
# cropped image
cropped_img = img[0:200, 0:300]
open_photo(cropped_img)

-1

In [ ]:
# gaussian blur
gaussian_blur_img = cv2.GaussianBlur(img, (19, 19), 0)

open_photo(gaussian_blur_img)

-1

In [ ]:
gaussian_blur_img_cvt = cv2.cvtColor(gaussian_blur_img, cv2.COLOR_BGR2GRAY) 

open_photo(gaussian_blur_img_cvt)

-1

In [ ]:
gaussian_blur_img_cvt_canny = cv2.Canny(gaussian_blur_img_cvt, 90, 90)

open_photo(gaussian_blur_img_cvt_canny)

-1

In [ ]:
kernel = np.ones((5, 5), np.uint8)
print(f'kernel: \n{kernel}')

gaussian_blur_img_cvt_canny_dilate = cv2.dilate(gaussian_blur_img_cvt_canny, kernel=kernel, iterations=2)

open_photo(gaussian_blur_img_cvt_canny_dilate)

kernel: 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


-1

In [ ]:
gaussian_blur_img_cvt_canny_dilate_erode = cv2.erode(gaussian_blur_img_cvt_canny, kernel=kernel, iterations=2)

open_photo(gaussian_blur_img_cvt_canny_dilate)

-1

## Learning Python OpenCV / Lesson #3 – Creating Objects and Outputting Information

In [4]:
photo = np.zeros((300, 300, 3), dtype='uint8')

In [5]:
photo

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(300, 300, 3), dtype=uint8)

In [4]:
open_photo(photo)

QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.githu

-1

In [ ]:
# RGB - standart
# BGR - OpenCV format
photo[:] = 255, 45, 78

In [7]:
open_photo(photo)

-1

In [ ]:
# RGB - standart
# BGR - OpenCV format
photo[:] = 175, 105, 255

In [9]:
open_photo(photo)

-1

In [ ]:
# RGB - standart
# BGR - OpenCV format
photo[:] = 255, 105, 175

In [11]:
open_photo(photo)

-1

In [14]:
# RGB - standart
# BGR - OpenCV format
photo[:] = 255, 255, 255
photo[150:200, 150:200] = 255, 105, 175

In [15]:
open_photo(photo)

-1

In [6]:
# RGB - standart
# BGR - OpenCV format
photo[:] = 255, 255, 255
cv2.rectangle(photo, (50, 70), (100, 100), (255, 105, 175), thickness=3)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [7]:
open_photo(photo)

QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.githu

In [8]:
# RGB - standart
# BGR - OpenCV format
photo[:] = 255, 255, 255
cv2.rectangle(photo, (50, 70), (100, 100), (255, 105, 175), thickness=cv2.FILLED)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [9]:
open_photo(photo)

In [ ]:
# RGB - standart
# BGR - OpenCV format
cv2.line(photo, (0, 0), (photo.shape[1], photo.shape[0]), (255, 234, 175), thickness=3)

array([[[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]]

In [13]:
open_photo(photo)

In [16]:
# RGB - standart
# BGR - OpenCV format
cv2.line(photo, (150, 0), (0, photo.shape[0]), (255, 200, 100), thickness=3)
cv2.line(photo, (0, 150), (photo.shape[1], 0), (255, 200, 100), thickness=3)

array([[[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       ...,

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]]

In [17]:
open_photo(photo)

In [20]:
# RGB - standart
# BGR - OpenCV format
cv2.line(photo, (150, 0), (150, photo.shape[0]), (0, 255, 0), thickness=3)
cv2.line(photo, (0, 150), (photo.shape[1], 150), (0, 200, 0), thickness=3)

array([[[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       ...,

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]]

In [22]:
open_photo(photo)

In [31]:
cv2.circle(photo, (photo.shape[1] // 2, photo.shape[0] // 2), 50, (255, 3, 238), thickness=3)

array([[[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       ...,

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]]

In [32]:
open_photo(photo)

In [33]:
text_on_photo = photo.copy()
cv2.putText(text_on_photo, 'A V S', (
    text_on_photo.shape[1] // 2 - 50,
    text_on_photo.shape[0] // 2 - 50,
    ),
    cv2.FONT_HERSHEY_TRIPLEX,
    1,
    (0, 0, 200),
)

array([[[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       [[255, 234, 175],
        [255, 234, 175],
        [255, 234, 175],
        ...,
        [255, 200, 100],
        [255, 200, 100],
        [255, 200, 100]],

       ...,

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]],

       [[255, 200, 100],
        [255, 200, 100],
        [255, 200, 100],
        ...,
        [255, 234, 175],
        [255, 234, 175],
        [255, 234, 175]]

In [34]:
open_photo(text_on_photo)

## Learning Python OpenCV / Lesson #4 – Image Transformation Functions

In [78]:
cap = cv2.VideoCapture('../data/videos/VID_408.mp4')

In [12]:
success, img = cap.read()

In [13]:
type(img)

numpy.ndarray

In [15]:
open_photo(img)
success

True

In [79]:
success = True
while True:
    success, img = cap.read()
    # if not success:
    #     break
    img = cv2.GaussianBlur(img, (9, 9), 0)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    img = cv2.Canny(img, 30, 30)

    kernel = np.ones((5, 5), np.uint8)
    img = cv2.dilate(img, kernel, iterations=1)
    
    img = cv2.erode(img, kernel, iterations=1)

    cv2.imshow('Result', img)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

    


error: OpenCV(4.13.0) /io/opencv/modules/imgproc/src/smooth.dispatch.cpp:618: error: (-215:Assertion failed) !_src.empty() in function 'GaussianBlur'


### Working with pictures

In [81]:
img_vertical_flip = cv2.flip(img, 1)
open_photo(img_vertical_flip)

In [82]:
img_horizontal_flip = cv2.flip(img, 0)
open_photo(img_horizontal_flip)

In [84]:
img_full_flip = cv2.flip(img, -1)
open_photo(img_full_flip)

In [85]:
returned_img = cv2.flip(img_full_flip, -1)
open_photo(returned_img)

In [11]:
rotated_img_30 = rotate(img, 30)
open_photo(rotated_img_30)

In [12]:
rotated_img_90 = rotate(img, 90)
open_photo(rotated_img_90)

In [13]:
rotated_img_180 = rotate(img, 180)
open_photo(rotated_img_180)

In [14]:
rotated_img_m90 = rotate(img, -90)
open_photo(rotated_img_m90)

In [7]:
img_transform = transform(img, 30, 200)
open_photo(img_transform)

QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/artem/development/ml/opencv_gosha_dudar/.venv/lib/python3.12/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.githu

In [8]:
img_transform = transform(img, -30, -100)
open_photo(img_transform)